web:
  build: .
  # "rerun --background --force-polling 'ruby router.rb'"
  command: ["rerun", "--background", "--force-polling", "ruby", "router.rb"]
  ports:
    - "4567:4567"
  links:
    - redis
  volumes:
    - .:/app

redis:
  image: redis
  ports:
    - "6379"
yard:
  build: .
  command: yard server --reload
  ports:
    - "8808:8808"